name: Workflow de Test Manual

# Această secțiune face ca butonul "Run workflow" să apară în interfață
on:
  workflow_dispatch:
    inputs:
      nume_utilizator:
        description: "Cui să îi spun salut?"
        required: true
        default: "DevOps Engineer"
      mediu:
        description: "Alege mediul de test"
        type: choice
        options:
          - Staging
          - QA
          - Local

jobs:
  test-manual:
    name: Executie Test
    runs-on: ubuntu-latest

    steps:
      - name: Pasul 1 - Salut
        run: echo "Salutare, ${{ github.event.inputs.nume_utilizator }}!"

      - name: Pasul 2 - Info Sistem
        run: |
          echo "Rulez pe un server: $RUNNER_OS"
          echo "Locația în care mă aflu: $(pwd)"

      - name: Pasul 3 - Verificare Mediu
        run: 'echo "Ai ales să testezi pe mediul: ${{ github.event.inputs.mediu }}"'

      - name: Pasul 4 - Finalizare
        run: echo "Testul a fost finalizat cu succes la ora $(date)"
